services:
  tuwunel:
    image: jevolk/tuwunel:latest
    container_name: tuwunel
    restart: unless-stopped
    ports:
      - "8008:8008"
    env_file:
      - ./sw1tch/config/tuwunel.env
    networks:
      - matrix_net
    volumes:
      - db:/var/lib/conduwuit/
      - ./sw1tch/data/.registration_token:/.registration_token:ro
      - /home/sij/tuwunel_backup:/backup
      - ./sw1tch/config/tuwunel.toml:/etc/tuwunel/tuwunel.toml:ro
    command: ["--config", "/etc/tuwunel/tuwunel.toml"]
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 16G
        reservations:
          cpus: '2.0'
          memory: 4G

  mautrix-signal:
    image: dock.mau.dev/mautrix/signal:latest
    container_name: mautrix-signal
    restart: unless-stopped
    networks:
      - matrix_net
    volumes:
      - /home/sij/mautrix/signal-bridge/docker:/data:z
    depends_on:
      - tuwunel

  diagnostics:
    image: nicolaka/netshoot
    container_name: diagnostics
    restart: unless-stopped
    networks:
      - matrix_net
    command: ["sleep", "infinity"]

volumes:
  db:
    external: true

networks:
  matrix_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.68.0.0/16
