services:
  unbound:
    image: mvance/unbound:latest
    container_name: unbound
    restart: unless-stopped
    networks:
      matrix_net:
        ipv4_address: 172.68.0.10
    volumes:
      - ./unbound.conf:/opt/unbound/etc/unbound/unbound.conf:ro
    healthcheck:
      test: ["CMD", "drill", "@127.0.0.1", "google.com"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M

  tuwunel:
    image: ghcr.io/matrix-construct/tuwunel:v1.1.0-release-all-x86_64-linux-gnu
    container_name: tuwunel
    restart: unless-stopped
    ports:
      - "8008:8008"
    dns:
      - 172.68.0.10
    networks:
      - matrix_net
    volumes:
      - db:/var/lib/conduwuit/
      - ./sw1tch/data/.registration_token:/.registration_token:ro
      - /home/sij/tuwunel_backup:/backup
      - ./sw1tch/config/tuwunel.toml:/etc/tuwunel/tuwunel.toml:ro
    environment:
      - RUST_LOG=tuwunel=warn,reqwest=error
    command: ["--config", "/etc/tuwunel/tuwunel.toml"]
    depends_on:
      unbound:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 16G
        reservations:
          cpus: '2.0'
          memory: 4G

  mautrix-signal:
    image: dock.mau.dev/mautrix/signal:latest
    container_name: mautrix-signal
    restart: unless-stopped
    networks:
      - matrix_net
    volumes:
      - /home/sij/mautrix/signal-bridge/docker:/data:z
    depends_on:
      - tuwunel

volumes:
  db:
    external: true

networks:
  matrix_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.68.0.0/16
